# nginx proxy address - http://172.17.0.1:8105

name: snapdrop
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  app:
    image: lscr.io/linuxserver/snapdrop:latest
    pull_policy: always
    container_name: snapdrop-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    logging: *default-logging
    networks:
      - snapdrop
    ports:
      - "172.17.0.1:8105:80"
    environment:
      TZ: ${TZ:-America/New_York}
      PUID: ${SERVICE_USER:-1000}
      PGID: ${SERVICE_GROUP:-1000}
    volumes:
      - ./volumes/config/snapdrop:/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  snapdrop:
    name: snapdrop
    external: false
